### ISSUE TITLE
the graph does not appear

### ISSUE THREAD

**Issue by tonagy** [intkhabahmed/multi_charts#16]
![image](https://user-images.githubusercontent.com/106313333/171265904-c7bd6271-a716-4836-90ff-ae1e014167bc.png)

i don't know what happen

**Comment by intkhabahmed** [comment]
Which platform is this?

**Comment by intkhabahmed** [comment]
Can you also add more details, code snippet?

**Comment by tonagy** [comment]
wait, maybe i fix the error. Thanks for the quick reply

**Comment by tonagy** [comment]
solved
