### ISSUE TITLE
How to make the labels tappable?

### ISSUE THREAD

**Issue by fauzipadlaw** [intkhabahmed/multi_charts#2]
I want to make the labels tappable, when I tap them it will navigate to other pages. How to make it possible?

**Comment by intkhabahmed** [comment]
@fauzipadlaw For that you would need to wrap your CustomPainter widget with GestureDetector widget and get the tapped element. It is the same method that Flare animation uses. Hope it will help you.

**Comment by fauzipadlaw** [comment]
@intkhabahmed Thank you for the fast response, but I still don't get it. How to implement that to this example? https://github.com/intkhabahmed/multi_charts/blob/master/lib/src/radar_chart/utils/paint_utils.dart

**Comment by intkhabahmed** [comment]
@fauzipadlaw You can take a look at this example https://gist.github.com/sma/c6a9111d58c3deb83711106cec6152ee 

It will give you some idea.

**Comment by fauzipadlaw** [comment]
@intkhabahmed Thank you, I try to learn it

**Comment by intkhabahmed** [comment]
ok, let me know if you have any further doubts

**Comment by echo326** [comment]
@fauzipadlaw Do you  make the labels tappable
