### ISSUE TITLE
Remove empty space surrounding the chart

### ISSUE THREAD

**Issue by erpriliano** [intkhabahmed/multi_charts#4]
Is there anyway I can remove empty space that surrounding the chart?

<img src="https://user-images.githubusercontent.com/49814974/68645528-ea02eb00-054a-11ea-8363-3fa70d04676b.png" height=600></img>

Here's the code :

```dart
double _height = MediaQuery.of(context).size.height * 0.55;

return RadarChart(
 maxHeight: _height,
 size: Size.infinite,
 maxValue: 5.0,
 values: _values,
 labels: _labels,
 fillColor: Colors.lightBlue[200],
 textScaleFactor: .03,
);
```

Already set the Size into .fromHeight and .fromWidth but still there's empty space surrounding it. Any ideas?

**Comment by intkhabahmed** [comment]
Hi, can you show me where are you returning the RadarChart?

**Comment by erpriliano** [comment]
I return `RadarChart()` inside `ListView()` in body section of this app's view. 

That's great and I'll wait and hope not for long for the update in your package. Thank you very much.

**Comment by intkhabahmed** [comment]
New version 0.1.1 is released. Please update to this version, your spacing issue will be solved
